default: &default
  adapter: postgresql

development:
  <<: *default
  database: rails-practice-collection-select-demo-development

test:
  <<: *default
  database: rails-practice-collection-select-demo-test
